### PR TITLE
Support tiptap v2 type format 

### PR DESCRIPTION
**Pull request by mmachatschek**

### CODE REVIEW

**Comment by dbbk** [comment]
Is this good to be merged?

**Comment by hanspagel** [comment]
I’ve got a nearly ready-to-use and v2-compatible rewrite of the package, that I plan to release this month. I’ve no plans to update this package here.

**Comment by dbbk** [comment]
Ah that would be great, thanks!

**Comment by hanspagel** [comment]
Closing in favor of https://github.com/ueberdosis/tiptap-php

**Pull request closed without merging**
