### PR TITLE
Service injection

### LINKED ISSUE #35: Marks and Nodes are instantiated as new Classes instead of Services
Because of Marks and Nodes are instantiated as new Classes, instead of services, it is impossible to inject other services in the Mark of Node. 
I think it would be better to have any kind of NodeRenderer/MarkRender, so you would be able to decorate or overwrite these renders.

### PR DESCRIPTION
**Pull request by cjprinse**
@hanspagel I just made the changes in a pull request.

If anything is unclear or you have some better naming or programming ideas, please do not hesitate to contact me.

Het library can also need some improvements in classifying nodes and marks (instead of just std-classes). But I just left that out of scope.

This fixes #35

### CODE REVIEW

**Comment by hanspagel** [comment]
That’s a ton of changes, and a ton of breaking changes. 

Would you mind to explain what the benefits of that change would be? I’m interested in what users would be able to do with the new implementation.

**Comment by cjprinse** [comment]
We (working  for a ecommerce company) use tiptap.io in our backend system, so our content department can adjust content of our website. 

For example: we custom made a link component, in which the user can select a product and then in het link mark, only the product id will be saved, not the actual link to the product. We use this strategy, because the link to the product can change over time, the product id won't.

So, we want to use this package (prosemirror-to-html) to render the link to the product, based on the link mark. We only have the product_id. So we want to inject our productRepository to lookup the product en get the slug of the product, so we can generate the actual link.

This is why we need service injection.

On the other hand, using this strategy will be faster, because it is not needed to instantiate a new Mark/Node every time. Just a few renderServices will be instantiates once when needed. If you use a framework (like Symfony, as we do) these services will be injected by proxy, and will only be loaded when used.

As a fallback, I made the Factory. So by default, all these Marks and Nodes are available, but you can inject a own registry to inject your own service rendered with their needed injections (like a productRepository for example).

Can you tell me the breaking changes, as I do not see them. Maybe I can make a workaround.

**Comment by hanspagel** [comment]
Thanks for clarification! Sounds good to me. I only scrolled through the changes quickly and thought there are two breaking changes:

* All custom nodes/marks have to extend another class.
* You need to rewrite the instantiation to use a factory.

But give me some time to take a closer look at your changes.

**Comment by cjprinse** [comment]
ping? When are you ready to review the code?

**Comment by hanspagel** [comment]
Thanks for your patience, and again thanks for your work on this! I try to summarize the changes of this PR:

**Pros**
1. The performance of this implementation will be slightly better.

**Cons**
1. Everyone who built a custom Node/Mark will have to change the code (`extend AbstractMarkRenderer` and Factory instead of `addMark/Node()`/`replaceMark/Node()` method).
2. I have to document the changes and adapt the pattern for `html-to-prosemirror` too.

While I think I’d probably start a new package following that pattern, I still don’t see the benefits that outweigh the work we ask people who wrote custom nodes and marks to do.

If you see a chance to implement your changes without any breaking changes or if you think I missed benefits of that implementation, don’t hesitate to follow up. Until then I’m closing this here.

For your use case I’d suggest to add a custom Link mark that replaces the product id with the correct link. That should do the trick for now. Thanks for your understanding!

**Comment by Zzombiee2361** [comment]
Ping! This seems exactly what I'm looking for and I have very similar use case like @cjprinse mentioned. Honestly I'm surprised this package doesn't have custom rendering. I don't really understand the code but couldn't you just make `Node` a wrapper to `AbstractMarkRenderer`?

> For your use case I’d suggest to add a custom Link mark that replaces the product id with the correct link. That should do the trick for now. Thanks for your understanding!

Could you elaborate more on this? I could probably use this in the meantime

**Comment by cjprinse** [comment]
The issue with the current implementation is the construction of nodes in the renderer. This prevents a developer from using external services when rendering nodes and marks. As far as I know, there is no other workaround then a Dependency Injection pattern. Best way to declare these classes is by using interfaces or abstract classes.

**Comment by hanspagel** [comment]
@Zzombiee2361 have you checked the README? There is a short example with a custom Node:
https://github.com/ueberdosis/prosemirror-to-html#custom-nodes

Same applies for marks. Let me know if something isn’t clear there, I’m happy to add more information.

**Comment by Zzombiee2361** [comment]
@hanspagel well, beside the confusing fact that an example of custom node is using `$markType` instead of `$nodeType`, the documentation also doesn't include how to use the methods like `tag` and `selfClosing`. But fortunately the source code is simple enough that I can understand by reading it.

Now like I said, my problem is similar to @cjprinse but a little bit complicated. I have a node with array of id as it's attribute, then I need this node to render as a `<div>` with multiple `<a>` as its children with the `href` read from database. Is it possible with current implementation?

I haven't seen all the changes in this pr, but boy is it a lot. Couldn't the change made more conservative like renaming `AbstractNodeRenderer` to the original `Node` and using original folder structure?

**Pull request closed without merging**
