### PR TITLE
Add support for title attribute to link mark

### PR DESCRIPTION
**Pull request by arthurperton**

### CODE REVIEW

**Comment by jasonvarga** [comment]
(A gentle ping for @hanspagel 😊 )

**Comment by hanspagel** [comment]
Oh, that somehow slipped through my GitHub notifications. Thanks for the PR @arthurperton! 🙌

**Comment by hanspagel** [comment]
Released ✅

https://github.com/ueberdosis/prosemirror-to-html/releases/tag/2.7.0

**Comment by jasonvarga** [comment]
Thanks!

**Comment by arthurperton** [comment]
Your'e welcome, thanks for the release!

**Pull request merged**
